Description: "This is a sample yaml cloud formation template."
Parameters:
  Ec2AmiId:
    Description: "EC2 AMI Id"
    Type: String
  Ec2InstanceType:
    Description: "Instance type of the instance"
    Type: String
  KeyPairName:
    Description: "Key pair name for accessing instance"
    Type: String
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      "AWS::CloudFormation::Init":
        config:
          packages:
            yum:
              openssh-server: []
              openssh-clients: []
    Properties:
      ImageId: !Ref Ec2AmiId
      KeyName: !Ref KeyPairName
      AvailabilityZone: us-east-1a
      SubnetId: !ImportValue VpcSubnetId
      InstanceType: !Ref Ec2InstanceType
      SecurityGroupIds:
        - !ImportValue VpcSecurityGroupId
      Tags:
        - Key: user
          Value: tkonarik
        - Key: stelligent-u-lesson
          Value: 4
        - Key: stelligent-u-lab
          Value: 4.1.1
  Ec2Instance2:
    Type: AWS::EC2::Instance
    Metadata:
      "AWS::CloudFormation::Init":
        config:
          packages:
            yum:
              openssh-server: []
              openssh-clients: []
    Properties:
      ImageId: !Ref Ec2AmiId
      KeyName: !Ref KeyPairName
      AvailabilityZone: us-east-1a
      SubnetId: !ImportValue VpcSubnet2Id
      InstanceType: !Ref Ec2InstanceType
      SecurityGroupIds:
        - !ImportValue VpcSecurityGroupId
      Tags:
        - Key: user
          Value: tkonarik
        - Key: stelligent-u-lesson
          Value: 4
        - Key: stelligent-u-lab
          Value: 4.1.1
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref Ec2Instance
Outputs:
  Ec2InstanceId:
    Description: "EC2 Instance Id"
    Value: !Ref Ec2Instance
    Export:
      Name: Ec2InstanceId
  Ec2InstancePrivateIp:
    Description: "EC2 Instance Id"
    Value: !GetAtt Ec2Instance.PrivateIp
    Export:
      Name: Ec2InstancePrivateIp
  Ec2Instance2Id:
    Description: "EC2 Instance Id"
    Value: !Ref Ec2Instance2
    Export:
      Name: Ec2Instance2Id
  Ec2Instance2PrivateIp:
    Description: "EC2 Instance Id"
    Value: !GetAtt Ec2Instance2.PrivateIp
    Export:
      Name: Ec2Instance2PrivateIp
