version: 0.2

env:
  shell: bash

batch:
  fast-fail: false | true
  # build-list:
  # build-matrix:
  # build-graph:

phases:
  pre_build:
    commands:
      - ls -la
      - aws cloudformation validate-template --template-body file://12-codepipeline/bucket.yaml
