Description: "This is a sample yaml cloud formation template."
Parameters:
  UserName:
    Description: "The UserName to be added to AWS"
    Type: String
    Default: practice-user
Conditions:
  S3BucketNamePrefix: !Equals [!Ref AWS::Region, 'us-east-1']
Resources:
  PracitceUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName
  PracticePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: PracticeIamPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:GetObjectVersion'
              - 's3:ListBucket'
            Resource: '*'
      Users:
        - !Ref PracitceUser
Outputs:
  ManagedPolicyArn:
    Description: "ARN for the created managed policy"
    Value: !Ref PracticePolicy
    Export:
      Name: ExportedManagedPolicyArn
