Parameters:
  lambdaFunctionName:
    Type: String
    Default: testFunction2
Resources:
  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: Example API Gateway
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: Api Gateway
#      Policy:
#        Version: "2012-10-17"
#        Statement:
#          - Effect: Allow
#            Action: "lambda:InvokeFunction"
#            Resource: "*"
  ApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations
          - lambdaArn: !GetAtt TestLambda.Arn
      ResourceId: !GetAtt ApiGatewayRestApi.RootResourceId
      RestApiId: !Ref ApiGatewayRestApi

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiGatewayMethod
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      StageName: test

  TestLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            const body = JSON.parse(event.body)
            const value = body.value ? body.value : "AWS";
            const response = {
              statusCode: 200,
              body: JSON.stringify('Hello ' + value + '!'),
            };
          return response;
          };
      FunctionName: !Ref lambdaFunctionName
      Handler: index.handler
      Role: !GetAtt LambdaExecuteRole.Arn
      Runtime: nodejs14.x
  LambdaExecuteRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
  RestApiLambdaPermission:
    Type: "AWS::Lambda::Permission"
    DependsOn:
    - ApiGatewayRestApi
    - TestLambda
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref TestLambda
      Principal: apigateway.amazonaws.com
