Parameters:
  BucketName:
    Type: String
    Default: testbucket-12-1-1
Resources:
  TestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
  CloudFormationPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "cloudformation:*"
              - "s3:*"
              - iam:PassRole
              - codebuild:StartBuild
              - codebuild:BatchGetBuilds
            Resource: "*"
  CloudFormationRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: "*"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - !Ref CloudFormationPolicy
  S3Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:*"
            Resource: "*"
  S3Role:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: "*"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - !Ref CloudFormationPolicy
  TestPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref BucketName
      RoleArn: !GetAtt CloudFormationRole.Arn
      Stages:
        -
          Name: Source
          Actions:
            -
              Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                Owner: travis-konarik-mphasis
                Repo: stelligent-u-work
                Branch: master
                OAuthToken: '{{resolve:secretsmanager:travis.konarik/GitHubSecret:SecretString:token}}'
                PollForSourceChanges: true
              RunOrder: 1
        -
          Name: Build
          Actions:
            -
              Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceArtifact
              Configuration:
                ProjectName: Validation
              RunOrder: 1
        -
          Name: Deploy
          Actions:
            -
              Name: DeployAction
              InputArtifacts:
                - Name: SourceArtifact
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: lab-12-1-1-deploy
                RoleArn: !GetAtt S3Role.Arn
                TemplatePath: SourceArtifact::12-codepipeline/bucket.yaml
                ParameterOverrides: '{"BucketNameParameter": "lab-12-1-1-deploy-bucket"}'
              RunOrder: 1
        -
          Name: Test
          Actions:
            -
              Name: TestAction
              ActionTypeId:
                Category: Test
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceArtifact
              Configuration:
                ProjectName: Verify
              RunOrder: 1
  BuildCodeBuildProjectPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "cloudformation:*"
              - logs:CreateLogStream
              - logs:CreateLogGroup
              - logs:PutLogEvents
              - "ec2:*"
              - "s3:*"
            Resource: "*"
  BuildCodeBuildProjectRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: "*"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - !Ref BuildCodeBuildProjectPolicy
  BuildCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Name: Validation
      ServiceRole: !GetAtt BuildCodeBuildProjectRole.Arn
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: public.ecr.aws/codebuild/amazonlinux2-x86_64-standard:3.0
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 10
  TestCodeBuildProjectPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "cloudformation:*"
              - logs:CreateLogStream
              - logs:CreateLogGroup
              - logs:PutLogEvents
              - "ec2:*"
              - "s3:*"
            Resource: "*"
  TestCodeBuildProjectRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: "*"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - !Ref TestCodeBuildProjectPolicy
  TestCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Name: Verify
      ServiceRole: !GetAtt TestCodeBuildProjectRole.Arn
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: public.ecr.aws/codebuild/amazonlinux2-x86_64-standard:3.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: 'verify-buildspec.yaml'
      TimeoutInMinutes: 10
